// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func pcOff() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<svg width=\"60\" height=\"100\" viewBox=\"0 0 120 160\" xmlns=\"http://www.w3.org/2000/svg\"><!-- Case --><rect x=\"28\" y=\"18\" width=\"64\" height=\"124\" rx=\"10\" fill=\"#1f2937\" stroke=\"#111827\" stroke-width=\"3\"></rect><!-- Side panel window --><rect x=\"36\" y=\"28\" width=\"48\" height=\"92\" rx=\"8\" fill=\"#111827\" stroke=\"#374151\" stroke-width=\"2\"></rect><!-- Fans (off) --><circle cx=\"60\" cy=\"52\" r=\"14\" fill=\"none\" stroke=\"#4b5563\" stroke-width=\"4\"></circle> <circle cx=\"60\" cy=\"52\" r=\"6\" fill=\"#4b5563\"></circle> <circle cx=\"60\" cy=\"84\" r=\"14\" fill=\"none\" stroke=\"#4b5563\" stroke-width=\"4\"></circle> <circle cx=\"60\" cy=\"84\" r=\"6\" fill=\"#4b5563\"></circle><!-- GPU (off) --><rect x=\"40\" y=\"102\" width=\"40\" height=\"10\" rx=\"4\" fill=\"#374151\"></rect> <rect x=\"78\" y=\"104\" width=\"6\" height=\"6\" rx=\"2\" fill=\"#4b5563\"></rect><!-- Power button (off) --><circle cx=\"80\" cy=\"136\" r=\"5\" fill=\"#111827\" stroke=\"#4b5563\" stroke-width=\"2\"></circle></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func pcOn() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<svg width=\"60\" height=\"100\" viewBox=\"0 0 120 160\" xmlns=\"http://www.w3.org/2000/svg\"><defs><!-- Soft glow --><filter id=\"rgbGlow\"><feGaussianBlur stdDeviation=\"4\" result=\"b\"></feGaussianBlur> <feMerge><feMergeNode in=\"b\"></feMergeNode> <feMergeNode in=\"SourceGraphic\"></feMergeNode></feMerge></filter><!-- RGB gradient --><linearGradient id=\"rgb\" x1=\"0\" y1=\"0\" x2=\"1\" y2=\"1\"><stop offset=\"0%\" stop-color=\"#22c55e\"></stop> <stop offset=\"50%\" stop-color=\"#60a5fa\"></stop> <stop offset=\"100%\" stop-color=\"#f97316\"></stop></linearGradient></defs><!-- Case --><rect x=\"28\" y=\"18\" width=\"64\" height=\"124\" rx=\"10\" fill=\"#1f2937\" stroke=\"#111827\" stroke-width=\"3\"></rect><!-- Side panel window --><rect x=\"36\" y=\"28\" width=\"48\" height=\"92\" rx=\"8\" fill=\"#0b1220\" stroke=\"#374151\" stroke-width=\"2\"></rect><!-- Fans (on) --><circle cx=\"60\" cy=\"52\" r=\"14\" fill=\"none\" stroke=\"url(#rgb)\" stroke-width=\"4\" filter=\"url(#rgbGlow)\"></circle> <circle cx=\"60\" cy=\"52\" r=\"6\" fill=\"#e5e7eb\" opacity=\"0.85\"></circle> <circle cx=\"60\" cy=\"84\" r=\"14\" fill=\"none\" stroke=\"url(#rgb)\" stroke-width=\"4\" filter=\"url(#rgbGlow)\"></circle> <circle cx=\"60\" cy=\"84\" r=\"6\" fill=\"#e5e7eb\" opacity=\"0.85\"></circle><!-- GPU body --><rect x=\"40\" y=\"102\" width=\"40\" height=\"10\" rx=\"4\" fill=\"#374151\"></rect><!-- GPU RGB light bar --><rect x=\"42\" y=\"105\" width=\"34\" height=\"4\" rx=\"2\" fill=\"url(#rgb)\" filter=\"url(#rgbGlow)\"></rect><!-- PCIe power / detail --><rect x=\"78\" y=\"104\" width=\"6\" height=\"6\" rx=\"2\" fill=\"#6b7280\"></rect><!-- Power button (on) --><circle cx=\"80\" cy=\"136\" r=\"5\" fill=\"#111827\" stroke=\"#22c55e\" stroke-width=\"2\" filter=\"url(#rgbGlow)\"></circle></svg>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func PCStatus(status bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"flex items-center justify-center\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if status {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"flex flex-col gap-2 justify-center items-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = pcOn().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"text-center text-sm\">Online</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"flex flex-col gap-2 justify-center items-center\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = pcOff().Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"text-center text-sm\">Offline</div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
