// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/loissascha/go-templ-template/internal/ui/layouts"

func Temps() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div><div class=\"w-48 h-24 relative\"><div class=\"rounded-t-full bg-neutral-400 absolute w-full h-full\"></div></div></div><div class=\"relative w-48 h-24 overflow-hidden\"><!-- background half circle --><div class=\"absolute inset-0 rounded-t-full bg-gray-300\"></div><!-- progress fill --><div class=\"absolute inset-0 rounded-t-full bg-green-500 origin-bottom-center transition-transform duration-500\" style=\"transform: rotate(120deg);\"></div><!-- inner cutout --><div class=\"absolute inset-2 rounded-t-full bg-white\"></div><!-- centered text --><div class=\"absolute inset-0 flex items-end justify-center pb-4\"><span class=\"text-xl font-semibold\">66%</span></div></div><div class=\"grid grid-cols-2 gap-4 p-4\"><div class=\"text-center\"><h1 class=\"text-4xl font-bold\">Temperatur</h1><span><span hx-get=\"/partials/components/temp\" hx-swap=\"innerHTML\" hx-trigger=\"load, every 10s\"></span> <strong>°C</strong></span></div><div class=\"text-center\"><h1 class=\"text-4xl font-bold\">Luftfeuchtigkeit</h1><span><span hx-get=\"/partials/components/humidity\" hx-swap=\"innerHTML\" hx-trigger=\"load, every 10s\"></span> <strong>%</strong></span></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layouts.LayoutNew().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
